INPUT:
  MASK_FORMAT: "bitmask"
  FORMAT: "RGB"
  RANDOM_FLIP: "horizontal"
OUTPUT_DIR: "./outfiles/test_small"
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.005
  STEPS: (60000, 100000)
  MAX_ITER: 160000
  CHECKPOINT_PERIOD: 1000
MODEL:
  META_ARCHITECTURE: RotatedMaskRCNN
  ANCHOR_GENERATOR:
    NAME: RotatedAnchorGenerator
  ROI_BOX_HEAD:
    NAME: FastRCNNConvFCHead
    BBOX_REG_WEIGHTS:
      - 10.0
      - 10.0
      - 5.0
      - 5.0
      - 5.0
    POOLER_TYPE: ROIAlignRotated
  ROI_HEADS:
    NAME: MRROIHeads
    SCORE_THRESH_TEST: 0.8
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 1
  ROI_MASK_HEAD:
    POOLER_TYPE: ROIAlignRotated
    POOLER_RESOLUTION: 28 #14
  RPN:
    BBOX_REG_WEIGHTS: (1.0,1.0,1.0,1.0,1.0)
  PROPOSAL_GENERATOR:
    NAME: RRPN
  MASK_ON: true
  WEIGHTS: ''
DATASETS:
  TEST:
  - test
  TRAIN:
  - train

# TEST:
  # EVAL_PERIOD: 100
